### ISSUE TITLE
HW2 - Reward to Go and advantage standardization

### ISSUE THREAD

**Issue by archit120** [silencial/DeepRL#3]
Hey,

I was doing HW2 and noticed something weird. I cloned your code to check the same and that is present with your solution too. Maybe you could shed some theoretical insight on why that might be? 

>Which value estimator has better performance without advantage-standardization:
the trajectory-centric one, or the one using reward-to-go?

While in your report you've written that reward-to-go performs better, when I created the plots using both your and mine code not using reward-to-go converges significantly faster to the maximum reward. Not using both advantage standardization and reward to go outperforms every other combination. I've verified this to be true on the default parameters. Do you have any idea why this might be?

**Comment by silencial** [comment]
From my report graph I think it is clear to see that reward-to-go and advantage-standardization performs better, especially for small batch.

Are you using the same command in my report to run? Or are you using different parameters?

**Comment by archit120** [comment]
Reward to go vs no reward to go without advantage-standardization: sb_rtg_na vs sb_no_rtg_na. "sb_no_rtg_na" is not present in the report so I did that graph myself using your code and it seems that without advantage-standardization reward-to-go is making things worse.

**Comment by silencial** [comment]
na means with advantage-standardization, dsa is without. You should check sb_rtg_dsa vs sb_no_rtg_dsa.

**Comment by archit120** [comment]
Oh wow, thanks a lot! I don't know how I read that wrong. Now it makes much more sense.

**Comment by archit120** [comment]
But part of the issue, while unrelated to HW, still remains. Using reward-to-go with advantage standardization is worse than not using reward-to-go with advantage standardization. Any clue why that might happen?

**Comment by silencial** [comment]
I am not sure but RL is pretty environment sensitive and random. If you want to find out, try running using different seeds and different environments.
